#!/usr/bin/env bash

POSITIONAL=()
DEBUG="false"
FORCE="false"
ROLLBACK="false"

function usage {
  if [ -n "${1}" ]; then
    echo -e "${1}"
    echo ''
  fi
  cat <<- EOF
		Usage: $(basename "$0") [<flags>] <node> [<command>]

		Flags:'
		  -h, --help                            display help
		  -d, --debug                           enable debug output
		  -r, --rollback                        rollback failed helm releases
		  -f, --force                           force reset helm state
	EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h | --help) usage "" ;;
    -d | --debug)
      DEBUG="true"
      shift
      ;;
    -f | --force)
      FORCE="true"
      shift
      ;;
    -r | --rollback)
      ROLLBACK="true"
      shift
      ;;
    *)
      POSITIONAL+=("$1") # save it in an array for later
      shift              # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

releases=""
releases="$(kubectl get hr -A | awk '/False/ {print $2 " -n " $1}')"
if [[ "${releases}" == "" ]]; then
  exit 0
fi

if [[ "${DEBUG}" == "true" ]]; then
  echo -e "RELEASES:\n${releases}"
fi

echo "${releases}" | xargs -r -L1 kubectl patch hr --type='json' -p='[{"op": "replace", "path": "/spec/suspend", "value": true}]'
if [[ "${ROLLBACK}" == "true" ]]; then
  [[ ${DEBUG} == "true" ]] && echo "Rolling back releases!"
  echo "${releases}" | awk '{print "helm-rollback -p " $0}' | xargs -r -I {} sh -c "{}"
fi
if [[ "${FORCE}" == "true" ]]; then
  [[ ${DEBUG} == "true" ]] && echo "Deleting Helm secrets"
  echo "${releases}" | awk '{print "kubectl delete secret -n " $3 " -l name="$1}' | xargs -r -I {} sh -c "{}"
fi
sleep 1
echo "${releases}" | xargs -r -L1 kubectl patch hr --type='json' -p='[{"op": "replace", "path": "/spec/suspend", "value": false}]'
