#! /usr/bin/env bash

NAMESPACE="${NAMESPACE:-default}"
DEBUG="false"
POSITIONAL=()
REV=""

function usage {
  if [ -n "${1}" ]; then
    echo -e "${1}"
    echo ''
  fi
  echo "Usage: $(basename "$0") [<flags>] <node> [<command>]"
  echo ''
  echo 'Flags:'
  echo '  -h, --help                            display help'
  echo '  -d, --debug                           enable debug output'
  echo '  -n, --namespace <name>                namespace name'
  echo '  -r, --revision <number>               revision number'
  echo ''
  exit 1
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
  -h | --help) usage "" ;;
  -d | --debug)
    DEBUG="true"
    shift
    ;;
  -n | --namespace)
    NAMESPACE="$2"
    shift 2
    ;;
  -r | --revision)
    REV="$2"
    shift 2
    ;;
  *)
    POSITIONAL+=("$1") # save it in an array for later
    shift              # past argument
    ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ "$DEBUG" == "true" ]]; then
  helm ls -a -n "${NAMESPACE}"
fi

failed=$(echo "${*}" | sed -r -e 's/(\s|\n|,|;)+/\n/g')

if [ -z "${failed}" ]; then
  failed=$(helm ls -a -n "${NAMESPACE}" | awk '!/(deployed|NAME)/ {print $1}')
fi

if [ -n "${failed}" ] && [ -n "${REV}" ]; then
  echo "Rolling back ${release} to revision ${REV}"
  helm rollback "${release}" -n "${NAMESPACE}" "${REV}"
  exit $?
fi

if [ -z "${failed}" ]; then
  echo "No failed releases found"
  exit 0
fi

if [[ "$DEBUG" == "true" ]]; then
  echo -e "Going to rollback:\n${failed}"
fi

for release in ${failed}; do
  revision=$(helm history "${release}" -n "${NAMESPACE}" | awk '/deployed/ {print $1}')
  if [[ "$DEBUG" == "true" ]]; then
    helm history "${release}" -n "${NAMESPACE}"
  fi
  if [ -n "${release}" ] && [ -n "${revision}" ]; then
    echo "Rolling back ${release} to revision ${revision}"
    helm rollback "${release}" -n "${NAMESPACE}" "${revision}"
  fi
done
