#!/usr/bin/env bash

NAMESPACE="${NAMESPACE:-default}"
DEBUG="false"
POSITIONAL=()
REV=""
PENDING="false"

function usage {
  if [ -n "${1}" ]; then
    echo -e "${1}"
    echo ''
  fi
  cat <<- EOF
		Usage: $(basename $0) [<flags>] <node> [<command>]

		Flags:
		  -h, --help                            display help
		  -d, --debug                           enable debug output
		  -p, --pending                         retry pending releases
		  -n, --namespace <name>                namespace name
		  -r, --revision <number>               revision number
	EOF
  if [ -n "${1}" ]; then
    exit 1
  fi
  exit 0
}

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h | --help) usage "" ;;
    -d | --debug)
      DEBUG="true"
      shift
      ;;
    -p | --pending)
      PENDING="true"
      shift
      ;;
    -n | --namespace)
      NAMESPACE="$2"
      shift 2
      ;;
    -r | --revision)
      REV="$2"
      shift 2
      ;;
    *)
      POSITIONAL+=("$1") # save it in an array for later
      shift              # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ "$DEBUG" == "true" ]]; then
  helm ls -a -n "${NAMESPACE}"
fi

failed=$(echo "${*}" | sed -r -e 's/(\s|\n|,|;)+/\n/g')

filter='(deployed|superseded|pending|NAME)'
if [[ "${PENDING}" == "true" ]]; then
  filter='(deployed|superseded|NAME)'
fi

if [ -z "${failed}" ]; then
  failed=$(helm ls -a -n "${NAMESPACE}" | awk -v filter="${filter}" '$0 !~ filter {print $1}')
fi

if [ -z "${failed}" ]; then
  echo "No failed releases found"
  exit 0
fi

if [ -n "${REV}" ]; then
  echo "Rolling back ${failed} to revision ${REV}"
  helm rollback "${failed}" -n "${NAMESPACE}" "${REV}"
  exit $?
fi

if [[ "$DEBUG" == "true" ]]; then
  echo -e "Going to rollback:\n${failed}"
fi

filter='(deployed|superseded)'
if [[ "${PENDING}" == "true" ]]; then
  filter='(deployed|superseded|pending)'
fi

for release in ${failed}; do
  revision=""
  if [[ "${PENDING}" != "true" ]]; then
    revision=$(helm history "${release}" -n "${NAMESPACE}" | awk '/deployed/ {print $1}')
  fi
  if [ -z "${revision}" ]; then
    revision=$(helm history "${release}" -n "${NAMESPACE}" | awk -v filter="${filter}" '$0 ~ filter {print $1}' | tail -n 1)
  fi
  if [[ "$DEBUG" == "true" ]]; then
    helm history "${release}" -n "${NAMESPACE}"
  fi
  if [ -n "${release}" ] && [ -n "${revision}" ]; then
    echo "Rolling back ${release} to revision ${revision}"
    helm rollback "${release}" -n "${NAMESPACE}" "${revision}"
  fi
done
