[[language]]
name = "go"
auto-format = true
formatter = {command = "goimports"}

[[language]]
name = "bash"
auto-format = true
formatter = {command = "shfmt", args = ["-i", "2", "-ci"]}

[[language]]
name = "markdown"
auto-format = true
formatter = {command = "prettier", args = ["--parser", "markdown"]}

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
auto-format = true
formatter = {command = "prettier", args = ["--parser", "typescript"]}

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
